FROM node:6.9
# replace this with your application's default port
EXPOSE 4200
#VOLUME ["blah or summat"]
RUN npm -g update
RUN npm install -g ember-cli
#RUN cd /mounted_in_container && ember new ember-quickstart
#RUN cd ember-quickstart
#CMD ember server
